### ISSUE TITLE
Issuse

### ISSUE THREAD

**Issue by ghost** [robske110/ServerSelector#2]
When doing /serverselector show or /serverlist gives a message saying 
"An unknown error occured while attempting to perform this command"

**Comment by robske110** [comment]
Please post the console output which occurs while executing the command

**Comment by ghost** [comment]
I checked console when it happened and there was no message

**Comment by robske110** [comment]
please check again carefully (reproduce the error again, if possible). There should be an error/warning message. You can also try to set this to 2 : https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/resources/pocketmine.yml#L101

**Comment by ghost** [comment]
It showed this time, here it is

Server thread/CRITICAL Unhandled exception executing command 'serverselector show' in serverselector show: Class 'pocketmine\form\MenuOption' not found
03.11 16:43:58 [Server] Server thread/CRITICAL Error: "Class 'pocketmine\form\MenuOption' not found" (EXCEPTION) in "ServerSelector/src/robske_110/ServerSelector/SelectorRenderer" at line 72
03.11 16:43:58 [Server] Server thread/DEBUG #0 ServerSelector/src/robske_110/ServerSelector/ServerSelector(127): robske_110\ServerSelector\SelectorRenderer->render(pocketmine\Player object)
03.11 16:43:58 [Server] Server thread/DEBUG #1 ServerSelector/src/robske_110/ServerSelector/ServerSelector(291): robske_110\ServerSelector\ServerSelector->openSelector(pocketmine\Player object)
03.11 16:43:58 [Server] Server thread/DEBUG #2 src/pocketmine/command/PluginCommand(58): robske_110\ServerSelector\ServerSelector->onCommand(pocketmine\Player object, pocketmine\command\PluginCommand object, string serverselector show, array Array())
03.11 16:43:58 [Server] Server thread/DEBUG #3 src/pocketmine/command/SimpleCommandMap(258): pocketmine\command\PluginCommand->execute(pocketmine\Player object, string serverselector show, array Array())
03.11 16:43:58 [Server] Server thread/DEBUG #4 src/pocketmine/Server(1984): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\Player object, string serverselector show)
03.11 16:43:58 [Server] Server thread/DEBUG #5 src/pocketmine/Player(2126): pocketmine\Server->dispatchCommand(pocketmine\Player object, string serverselector show)
03.11 16:43:58 [Server] Server thread/DEBUG #6 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(220): pocketmine\Player->chat(string /serverselector show)

**Comment by robske110** [comment]
Ah, I should've mentioned that this plugin needs the forms-api branch https://github.com/pmmp/PocketMine-MP/tree/forms-api
I have attached a Pocketmine-MP.phar which you can use with this plugin.
[PocketMine-MP_1.7dev.phar.zip](https://github.com/robske110/ServerSelector/files/1442433/PocketMine-MP_1.7dev.phar.zip) (or, if you want to run from source https://github.com/robske110/pmmp-PocketMine-MP/tree/forms-api)

**Comment by ghost** [comment]
It works! Thank you
